# Generated by Django 3.0.4 on 2020-10-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20200728_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('winner', 'Winner')], max_length=100, null=True),
        ),
    ]
