# Generated by Django 3.0.4 on 2020-10-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20201011_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='applicant',
        ),
    ]
