# Generated by Django 3.0.4 on 2020-10-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20200802_1543'),
        ('entry', '0004_remove_entry_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Competition'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
