# Generated by Django 3.0.4 on 2020-10-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_auto_20201011_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('winner', 'Winner')], default='', max_length=100),
        ),
    ]
