# Generated by Django 3.0.4 on 2020-10-11 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0003_auto_20200802_1543'),
        ('entry', '0006_auto_20201011_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.Competition'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(blank=True, choices=[('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('winner', 'Winner')], max_length=100, null=True),
        ),
    ]
