# Generated by Django 3.0.8 on 2020-07-28 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, null=True)),
                ('max_entry', models.IntegerField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('reg_fee', models.IntegerField(default=0)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(max_length=100)),
                ('locality', models.CharField(default='General', max_length=100)),
                ('prize', models.CharField(blank=True, max_length=200, null=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
