# Generated by Django 3.0.8 on 2020-08-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
