# Generated by Django 3.0.8 on 2020-08-02 14:43

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_competition_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
